apiVersion: v1 # Para vincular a um pv as configs de spec devem ser exatamente iguais
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
